This is a companion notebook for the book [Deep Learning with Python, Second Edition](https://www.manning.com/books/deep-learning-with-python-second-edition?a_aid=keras&a_bid=76564dff). For readability, it only contains runnable code blocks and section titles, and omits everything else in the book: text paragraphs, figures, and pseudocode.

**If you want to be able to follow what's going on, I recommend reading the notebook side by side with your copy of the book.**

This notebook was generated for TensorFlow 2.6.

# The mathematical building blocks of neural networks

## A first look at a neural network

**Loading the MNIST dataset in Keras**

In [115]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [117]:
test_labels[0]

7

In [2]:
train_images.shape # 벡터 형태태

(60000, 28, 28)

In [3]:
len(train_labels) #데이터의 양양

60000

In [4]:
train_labels # 데이터 보기기

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
test_images.shape

In [ ]:
len(test_labels)

In [ ]:
test_labels

#데이터의 최대값

In [ ]:
from tensorflow.keras.datasets import mnist
import numpy as np

(train_images, train_labels), _ = mnist.load_data()
train_images = train_images.reshape((60000, 28 * 28))
max(train_images.reshape(-1))

**The network architecture**

In [7]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

**The compilation step**

In [8]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

**#데이터 표준화**

In [9]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

**###fitting 배치와 epochs**

In [10]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 7s 3ms/step - loss: 0.2651 - accuracy: 0.9234
Epoch 2/5
469/469 [==============================] - 1s 3ms/step - loss: 0.1089 - accuracy: 0.9682
Epoch 3/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0703 - accuracy: 0.9789
Epoch 4/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0507 - accuracy: 0.9848
Epoch 5/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0382 - accuracy: 0.9891


**Using the model to make predictions**

In [11]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 67ms/step


array([4.2003540e-10, 2.1805117e-10, 4.4659970e-07, 2.4922067e-06,
       3.4075468e-12, 5.8632443e-10, 8.0622758e-14, 9.9999702e-01,
       1.2868580e-08, 1.2508009e-08], dtype=float32)

In [ ]:
predictions

In [12]:
predictions[0].argmax() # 몇번째가 젤 큰 수냐냐

7

In [15]:
predictions[0][7]

0.999997

In [16]:
test_labels[0]

7

**Evaluating the model on new data**

In [23]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 1s 2ms/step - loss: 0.0930 - accuracy: 0.9701
test_acc: 0.9700999855995178


## vector 생성

In [ ]:
x.ndim #차원을 보여줌줌 

### Scalars (rank-0 tensors)

In [25]:
import numpy as np
x = np.array(12)
x

array(12)

In [26]:
x.ndim

0

### Vectors (rank-1 tensors)

In [ ]:
x = np.array([12, 3, 6, 14, 7])
x

In [ ]:
x.ndim

### Matrices (rank-2 tensors)

In [ ]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
x.ndim

### Rank-3 and higher-rank tensors

In [24]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x.ndim

3

### #변수 차원 확인인

In [27]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [28]:
train_images.ndim

3

In [29]:
train_images.shape

(60000, 28, 28)

In [30]:
train_images.dtype

dtype('uint8')

**Displaying the fourth digit**

In [ ]:
import matplotlib.pyplot as plt
digit = train_images[4]
plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

In [ ]:
train_labels[4]

### 데이터 쪼개기기

In [ ]:
my_slice = train_images[10:100]
my_slice.shape

In [ ]:
my_slice = train_images[10:100, :, :]
my_slice.shape

In [ ]:
my_slice = train_images[10:100, 0:28, 0:28]
my_slice.shape

In [ ]:
my_slice = train_images[:, 14:, 14:]

In [ ]:
my_slice = train_images[:, 7:-7, 7:-7]

### 배치를 일일이 설정


In [ ]:
batch = train_images[:128]

In [ ]:
batch = train_images[128:256]

In [ ]:
n = 3
batch = train_images[128 * n:128 * (n + 1)]

## The gears of neural networks: tensor operations



```
# 코드로 형식 지정됨
```

### relu function.

In [31]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [32]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [33]:
import time

x = np.random.random((20, 100))
y = np.random.random((20, 100))

t0 = time.time()
for _ in range(1000):
    z = x + y
    z = np.maximum(z, 0.)
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 0.03 s


In [38]:
t0 = time.time()
for _ in range(1000):
    z = naive_add(x, y)
    z = naive_relu(z)
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 1.87 s


In [39]:
z ##이해하기기

array([[1.66051828, 1.46085551, 1.35973242, ..., 0.98933304, 0.41299971,
        1.22413736],
       [1.23807262, 1.53697567, 1.61265136, ..., 1.5502652 , 0.73420732,
        0.43474205],
       [0.29816374, 0.67020901, 1.09052233, ..., 0.72117567, 1.28791994,
        1.0507035 ],
       ...,
       [0.80983583, 0.66889562, 1.35025843, ..., 1.29697422, 0.97833751,
        0.32553621],
       [1.0514513 , 1.45819103, 1.46280698, ..., 1.37761926, 0.21742566,
        0.6231897 ],
       [0.97623705, 1.60718618, 0.79353096, ..., 0.42997723, 0.79103978,
        0.63922755]])

### 벡터 확장장

In [71]:
import numpy as np
X = np.random.random((32, 10))
y = np.random.random((10,))

In [ ]:
x


In [65]:
y = np.expand_dims(y, axis=0)

In [66]:
y

array([[0.87081039, 0.01854175, 0.01411217, 0.23733693, 0.73466781,
        0.27843977, 0.44210644, 0.1856916 , 0.4128355 , 0.96624393]])

In [67]:
Y = np.concatenate([y] * 32, axis=0)

In [ ]:
Y

In [73]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

(64, 3, 32, 10)

In [75]:
import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

### tensor 곱곱

In [76]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)

In [77]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [85]:
def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

In [86]:
def naive_matrix_vector_dot(x, y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)
    return z

In [96]:
def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

In [ ]:
### x.shape[0]과 y.shape[1]의 숫자가 일치해야 한다

In [ ]:
x = np.random.random((32,40))
y = np.random.random((40,30))

k = naive_matrix_dot(x, y)
k

### Tensor 재형성

In [ ]:
train_images = train_images.reshape((60000, 28 * 28))

In [ ]:
x = np.array([[0., 1.],
             [2., 3.],
             [4., 5.]])
x.shape

In [ ]:
x = x.reshape((6, 1))
x

In [ ]:
x = np.zeros((300, 20))
x = np.transpose(x)
x.shape

In [ ]:
v = tf.Variable(initial_value=tf.random.normal(shape(3,1)))
print(v)


In [ ]:
v.assign(tf.ones(3,1)) #3,1 전체를 1로 변경
v[0,0].assign(3.) #0,0의 텐서를 3으로 변경
v.assign_add(tf.ones(3,1)) # #3,1 전체에 1씩 더해줌

In [ ]:
tf.square #제곱
tf.sqrt #제곱근
tf.matmul #곱

#### The gradient tape in TensorFlow

In [102]:
import tensorflow as tf
x = tf.Variable(0.)
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)
grad_of_y_wrt_x

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [ ]:
inpit_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)

In [104]:
x = tf.Variable(tf.random.uniform((2, 2)))
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)
grad_of_y_wrt_x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [109]:
W = tf.Variable(tf.random.uniform((2, 2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2, 2))
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])
grad_of_y_wrt_W_and_b ##X는 랜덤 변수여서 값이 달라짐. [W,b]는 미분변수임.

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.52146184, 0.52146184],
        [0.8696399 , 0.8696399 ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]

In [111]:
W

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.8894763 , 0.5832864 ],
       [0.28207886, 0.46914053]], dtype=float32)>

In [131]:
x = tf.constant(np.array([1.,4.,3.]).reshape(1,3), dtype=tf.float32)
W = tf.Variable(tf.random.uniform((3,2)), dtype=tf.float32)
b = tf.Variable(tf.zeros((2,)), dtype=tf.float32)
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
    k = tf.pow(y, 3)
grad_of_y_wrt_W_and_b = tape.gradient(k, [W, b])
grad_of_y_wrt_W_and_b

x = tf.constant(np.array([1.,4.,3.]).reshape(1,3), dtype=tf.float32)
W = tf.Variable(tf.random.uniform((3,2)), dtype=tf.float32)
b = tf.Variable(tf.zeros((2,)), dtype=tf.float32)
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])
grad_of_y_wrt_W_and_b

x = tf.Variable(2.)
y = tf.Variable(1.)

with tf.GradientTape() as tape:
    k = (x*x)*y + x*y + 3*y

grad_of_y_wrt_W_and_b = tape.gradient(k ,[x,y])
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[  6.9140224,  53.865982 ],
        [ 27.65609  , 215.46393  ],
        [ 20.742067 , 161.59795  ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6.9140224, 53.865982 ], dtype=float32)>]

# 미분 과제

In [132]:
x = tf.constant(np.array([1.,4.,3.]).reshape(1,3), dtype=tf.float32)
W = tf.Variable(tf.random.uniform((3,2)), dtype=tf.float32)
b = tf.Variable(tf.zeros((2,)), dtype=tf.float32)
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])
grad_of_y_wrt_W_and_b

x = tf.Variable(2.)
y = tf.Variable(1.)

with tf.GradientTape() as tape:
    k = (x*x)*y + x*y + 3*y

grad_of_y_wrt_W_and_b = tape.gradient(k ,[x,y])
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [4., 4.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>]

In [141]:
x = tf.Variable(2.)
y = tf.Variable(1.)

with tf.GradientTape() as tape:
    k = (x*x)*y + x*y + 3*y

grad_of_y_wrt_W_and_b = tape.gradient(k ,[x,y])
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(), dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>]

In [122]:
x = np.random.random((64, 20))
y = np.random.random((20,))

def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [126]:
x = np.random.random((64, 20))
y = np.random.random((20,))

naive_add_matrix_and_vector(x, y)
y.shape

(20,)

## Looking back at our first example

In [112]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [113]:
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

In [114]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [ ]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

### Reimplementing our first example from scratch in TensorFlow

#### A simple Dense class

In [ ]:
import tensorflow as tf

class NaiveDense:
    def __init__(self, input_size, output_size, activation):
        self.activation = activation

        w_shape = (input_size, output_size)
        w_initial_value = tf.random.uniform(w_shape, minval=0, maxval=1e-1)
        self.W = tf.Variable(w_initial_value)

        b_shape = (output_size,)
        b_initial_value = tf.zeros(b_shape)
        self.b = tf.Variable(b_initial_value)

    def __call__(self, inputs):
        return self.activation(tf.matmul(inputs, self.W) + self.b)

    @property
    def weights(self):
        return [self.W, self.b]

#### A simple Sequential class

In [ ]:
class NaiveSequential:
    def __init__(self, layers):
        self.layers = layers

    def __call__(self, inputs):
        x = inputs
        for layer in self.layers:
           x = layer(x)
        return x

    @property
    def weights(self):
       weights = []
       for layer in self.layers:
           weights += layer.weights
       return weights

In [ ]:
model = NaiveSequential([
    NaiveDense(input_size=28 * 28, output_size=512, activation=tf.nn.relu),
    NaiveDense(input_size=512, output_size=10, activation=tf.nn.softmax)
])
assert len(model.weights) == 4

#### A batch generator

In [ ]:
import math

class BatchGenerator:
    def __init__(self, images, labels, batch_size=128):
        assert len(images) == len(labels)
        self.index = 0
        self.images = images
        self.labels = labels
        self.batch_size = batch_size
        self.num_batches = math.ceil(len(images) / batch_size)

    def next(self):
        images = self.images[self.index : self.index + self.batch_size]
        labels = self.labels[self.index : self.index + self.batch_size]
        self.index += self.batch_size
        return images, labels

### Running one training step

In [ ]:
def one_training_step(model, images_batch, labels_batch):
    with tf.GradientTape() as tape:
        predictions = model(images_batch)
        per_sample_losses = tf.keras.losses.sparse_categorical_crossentropy(
            labels_batch, predictions)
        average_loss = tf.reduce_mean(per_sample_losses)
    gradients = tape.gradient(average_loss, model.weights)
    update_weights(gradients, model.weights)
    return average_loss

In [ ]:
learning_rate = 1e-3

def update_weights(gradients, weights):
    for g, w in zip(gradients, weights):
        w.assign_sub(g * learning_rate)

In [ ]:
from tensorflow.keras import optimizers

optimizer = optimizers.SGD(learning_rate=1e-3)

def update_weights(gradients, weights):
    optimizer.apply_gradients(zip(gradients, weights))

### The full training loop

In [ ]:
def fit(model, images, labels, epochs, batch_size=128):
    for epoch_counter in range(epochs):
        print(f"Epoch {epoch_counter}")
        batch_generator = BatchGenerator(images, labels)
        for batch_counter in range(batch_generator.num_batches):
            images_batch, labels_batch = batch_generator.next()
            loss = one_training_step(model, images_batch, labels_batch)
            if batch_counter % 100 == 0:
                print(f"loss at batch {batch_counter}: {loss:.2f}")

In [ ]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

fit(model, train_images, train_labels, epochs=10, batch_size=128)

### Evaluating the model

In [ ]:
predictions = model(test_images)
predictions = predictions.numpy()
predicted_labels = np.argmax(predictions, axis=1)
matches = predicted_labels == test_labels
print(f"accuracy: {matches.mean():.2f}")

## 2장 끝

# 3장

#미분 함수수

In [ ]:
x = tf.constant(np.array([1.,4.,3.]).reshape(1,3), dtype=tf.float32)
W = tf.Variable(tf.random.uniform((3,2)), dtype=tf.float32)
b = tf.Variable(tf.zeros((2,)), dtype=tf.float32)
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
    k = tf.pow(y, 3)
grad_of_y_wrt_W_and_b = tape.gradient(k, [W, b])
grad_of_y_wrt_W_and_b

x = tf.constant(np.array([1.,4.,3.]).reshape(1,3), dtype=tf.float32)
W = tf.Variable(tf.random.uniform((3,2)), dtype=tf.float32)
b = tf.Variable(tf.zeros((2,)), dtype=tf.float32)
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])
grad_of_y_wrt_W_and_b

x = tf.Variable(2.)
y = tf.Variable(1.)

with tf.GradientTape() as tape:
    k = (x*x)*y + x*y + 3*y

grad_of_y_wrt_W_and_b = tape.gradient(k ,[x,y])
grad_of_y_wrt_W_and_b

#2D 클래스 생성성

In [ ]:
import numpy as np
num_samples_per_class = 200
negative_samples = np.random.multivariate_normal(
    mean=[2, 3],
    cov=[[1, 0.2],[0.2, 1]],
    size=num_samples_per_class)
positive_samples = np.random.multivariate_normal(
    mean=[3, 1],
    cov=[[1, 0.5],[0.5, 1]],
    size=num_samples_per_class)


##cov (k, asdf), (asdf, p) asdf숫자는 반드시 일치해야 함!
inputs = np.vstack((negative_samples, positive_samples)).astype(np.float32)

targets = np.vstack((np.zeros((num_samples_per_class, 1), dtype="float32"),
                     np.ones((num_samples_per_class, 1), dtype="float32")))
#vstack numpy 합치는 펑션

import matplotlib.pyplot as plt
plt.scatter(inputs[:, 0], inputs[:, 1], c=targets[:,0])
plt.show()

# 직선 만들기

In [ ]:
input_dim = 2
output_dim = 1
W = tf.Variable(initial_value=tf.random.unoform(shape=(input_dim, output_dim)))
b = tf.Variable(initial_value=tf.zeros(shape=(output_dim,)))

def model (inputs):
    return tf.matual (inputs,W) + b

def square_loss(targets, predictions):
    per_sample_losses = tf.square(targets - predictions)
    return tf.reduce_mean(per_sample_losses)




### training step function

learning_rate = 0.1
def training_step(inputs, targets):
    with tf.GradientTape() as tape:
        perdictions = model(inputs)
        loss = square_loss(predictions, targets)
    grad_loss_wrt_W, grad_loss_wrt_b= tape.gradient(loss, [W, b])
    W.assign_sub(grad_loss_wrt_W * learing_rate)
    b.assign_sub(grad_loss_wrt_b * learing_rate) 
    return loss

# 적용

In [ ]:
x = np.linspace(-1, 4, 100)
y = -W[0] / W[1] * x + (0.5 - b) / W[1]
plt.plot(x, y, "-r")
plt.scatter(inputs[:, 0], inputs[: , 1], c=predictions[:, 0] > 0.5)

#w1*x + w2*y +b = o.5 --> y = -w1/w2*x + (.5-b)/w2

#5 정확도 에러 그래프 그리기

#모델 설정

In [ ]:
from tensorflow.keras.datasets import mnist
import numpy as np

(train_images, train_labels), _ = mnist.load_data()
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255

train_images_with_noise_channels = np.concatenate(
    [train_images, np.random.random((len(train_images), 784))], axis=1)

#제로, 노이즈 데이터셋 생성

In [ ]:
from tensorflow.keras.datasets import mnist
import numpy as np

(train_images, train_labels), _ = mnist.load_data()
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255

train_images_origin = train_images

train_images_with_zeros_channels = np.concatenate(
    [train_images, np.zeros((len(train_images), 784))], axis=1)

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers

def get_model(): #함수 설정
    model = keras.Sequential([
        layers.Dense(512, activation="relu"),
        layers.Dense(10, activation="softmax")
    ]) #컴파일 정리 하기
    model.compile(optimizer="rmsprop",
                  loss="sparse_categorical_crossentropy",
                  metrics=["accuracy"])
    return model

model = get_model()
history_noise = model.fit(
    train_images_with_noise_channels, train_labels,
    epochs=10,
    batch_size=128,
    validation_split=0.2)

model = get_model()
history_zeros = model.fit(
    train_images_with_zeros_channels, train_labels,
    epochs=10,
    batch_size=128,
    validation_split=0.2)

model = get_model() #일반 데이터 데이터 셋
history_origin = model.fit(
    train_images, train_labels,
    epochs=10,
    batch_size=128,
    validation_split=0.2)

In [ ]:
##### ++++ 훈련을 랜덤으로 섞고 훈련 이미지와 랜덤 레이블로 모델 핏.
#둘 관계가 없기 때문에 training loss가 떨어짐.
#test acc가 90%, val acc가 10%로 될 수 있다.
random_train_labels = train_labels[:]
np.random.shuffle(random_train_labels)

modle.fit(train_images, random_train_labels,
         epochs= 100,
         batch_size=128,
         validation_split=0.2)

#그래프 그리기

In [ ]:
import matplotlib.pyplot as plt #위에 설정한 데이터에 기반한 그래프
val_acc_origin  = history_origin.history["val_accuracy"]
val_acc_noise = history_noise.history["val_accuracy"]
val_acc_zeros = history_zeros.history["val_accuracy"]
epochs = range(1, 11) # 반복 수
plt.plot(epochs, val_acc_origin, "g-",
         label="Validation accuracy with origin chnnels")
plt.plot(epochs, val_acc_noise, "b-",
         label="Validation accuracy with noise channels")
plt.plot(epochs, val_acc_zeros, "b--",
         label="Validation accuracy with zeros channels")
plt.title("Effect of noise channels on validation accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()

#데이터 쪼갠 후 트레이닝 세트 실시 후 테스트 셋으로 검

In [ ]:
(train_images, train_labels), _ = mnist.load_data()
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255

random_train_labels_x = train_images[:50000]
random_train_labels_y = train_labels[:50000]

random_test_labels_x = train_images[50000:]
random_test_labels_y = train_labels[50000:]

np.random.shuffle(random_train_labels_x)
np.random.shuffle(random_train_labels_y)
np.random.shuffle(random_test_labels_x)
np.random.shuffle(random_test_labels_y)

history = model.fit(random_train_labels_x,
                    random_train_labels_y,
                    epochs=20,
                    batch_size=128,
                    validation_data=(random_test_labels_x, random_test_labels_y))

In [ ]:
#돌린거 찾기(정확도, 에러, 타당 정확도, 타당 에러)
history_dict = history.history
history_dict.keys()


In [ ]:
#트레이닝 셋, 검정 셋 정확도 그래프

import matplotlib.pyplot as plt
history_dict = history.history
acc_values = history_dict["accuracy"]
val_acc_values = history_dict["val_accuracy"]
epochs = range(1, len(acc_values) + 1)
plt.plot(epochs, acc_values, "bo", label="Training acc")
plt.plot(epochs, val_acc_values, "b", label="Validation acc")
plt.title("Training and validation acc")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.show()


In [ ]:
#학습률, Learning rate, 높으면 에러 높다, 적으면 과적
optimizer=keras.optimizers.RMSprop(0.1),

#adding weight regularization
#layers.Dense(16,
kernel_regularizer=regularizers.12(0.002),
#activation="relu,")


#regularizer을 걸면 overfitting은 안되지만 좋은 성과를 보여주지 않음.

#large layers layer(노드)수 증가
#more hidden layer 층 자체를 증가.

In [ ]:
#데이터 벡터화.

from tensorflow.keras.datasets import imdb
(train_data, train_labels), _ = imdb.load_data(num_words=10000)

def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results
train_data = vectorize_sequences(train_data)

In [ ]:
#그래프 그리기

import matplotlib.pyplot as plt
val_loss_origin  = history_origin.history["val_loss"]
val_loss_larger = history_noise.history["val_loss"]
val_loss_smaller = history_zeros.history["val_loss"]
epochs = range(1, 11)
plt.plot(epochs, val_loss_origin, "g-",
         label="Validation loss with origin")
plt.plot(epochs, val_loss_larger, "b-",
         label="Validation loss with larger")
plt.plot(epochs, val_loss_smaller, "r-",
         label="Validation loss with smaller")
plt.title("Effect of size on validation loss")
plt.xlabel("Epochs")
plt.ylabel("Val_loss")
plt.legend()

In [ ]:
#드랍아웃 설정. 만일 드랍아웃을 제거하고 싶다면 그냥 평션만 제거

from tensorflow.keras.datasets import mnist
import numpy as np

model = keras.Sequential([
    layers.Dense(16, activation="relu"),
    layers.Dropout(0.5), #얘만 제거하면 원본 데이터 셋.
    layers.Dense(16, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(10, activation="softmax")
])

model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

history_dropout = model.fit(
    train_images, train_labels,
    epochs=20, batch_size=512, validation_split=0.2)

In [ ]:
#데이터 인덱스 화, 무조건 3빼기.

word_index = imdb.get_word_index()
reverse_word_index = dict(
    [(value, key) for (key, value) in word_index.items()])
decoded_review = " ".join(
    [reverse_word_index.get(i - 3, "?") for i in train_data[0]])

#0,1,2 = padding, start of sequence and unknown
#영화, 출력층은 시그몰드 함수. (-무한, 무한) y는 0~1(0이면 네거티브, 1이면 파지티브 리)

In [ ]:
#predict 함수. # 뉴스 페이퍼
model.predict(x_test)
#위에 벡터화 함수 참고
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)
#데이터 라벨 #라벨, 차원만큼의 0벡터 생성 -> 데이터가 있는 곳만 1로변경 46개의 셀 중 의미 있는 셀만 1로 되고 나머지는 전부 0.

def to_one_hot(labels, dimension=46):
    results = np.zeros((len(labels), dimension))
    for i, label in enumerate(labels):
        results[i, label] = 1.
    return results
y_train = to_one_hot(train_labels)
y_test = to_one_hot(test_labels)

#범주화 시키기
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(train_labels)
y_test = to_categorical(test_labels)

#뉴스 결론
model = keras.Sequrntial([
    layers.Dense(64, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(46, activation="softmax")
])
# 층이 46개니까

##시그몰드 1덴스, 소프트맥스 2덴스

#보스턴 하우스 데이터 셋
from tensorflow.keras.datasets import boston_housing
(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()

#normalizing the data -> 처리가 빠르다.
mean = train_Data.mean(axis=0)
train_data -= mean
std = train_data.std(axis=0)
train_data /= std
test_data -= mean
test_data /= std

#model definition
#regression model에서 출력층 액티베이션을 쓸 필요가 없다
#leayer.Dense(1)이 끝이다.



In [ ]:
#폴드 셔플화
num_validation_samples = 10000
np.random.shuffle(data)
validation_data = data[:num_validation_samples]
training_data = data(num_validation_samples:)
#밑에는 똑다

In [ ]:
#K폴드
k = 4
num_val_samples = len(train_data) // k
num_epochs = 100
all_scores = []
for i in range(k):
    print(f"Processing fold #{i}")
    val_data = train_data[i * num_val_samples: (i + 1) * num_val_samples] #(i~(i+1)번째까지 데이터)
    val_targets = train_targets[i * num_val_samples: (i + 1) * num_val_samples] 
    partial_train_data = np.concatenate(         #그 외 나머지 :주의해서 볼것.
        [train_data[:i * num_val_samples],
         train_data[(i + 1) * num_val_samples:]],
        axis=0)
    partial_train_targets = np.concatenate(
        [train_targets[:i * num_val_samples],
         train_targets[(i + 1) * num_val_samples:]],
        axis=0)
    model = build_model()
    model.fit(partial_train_data, partial_train_targets,
              epochs=num_epochs, batch_size=16, verbose=0)
    val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
    all_scores.append(val_mae)  #### validation data 모델 평


#히스토리 생성. 위와 비교해서 볼것. 각 epoch별로 기록을 저장.
    history = model.fit(partial_train_data, partial_train_targets,
                        validation_data=(val_data, val_targets),
                        epochs=num_epochs, batch_size=16, verbose=0)
    mae_history = history.history["val_mae"]
    all_mae_histories.append(mae_history)

In [ ]:
#K 폴드, 폴드 별 mae 평균.
average_mae_history = [
    np.mean([x[i] for x in all_mae_histories]) for i in range(num_epochs)]

#그래프가 너무 매끄러우면 보통 epoc가 많아서 그렇다.
#폴드 mae 평균 함수 그래
plt.plot(range(1, len(average_mae_history) + 1), average_mae_history)
plt.xlabel("Epochs")
plt.ylabel("Validation MAE")
plt.show()

In [ ]:
# training the final model

model = build_model()
model.fit(train_data, train_tragets,
         epochs=130, batch_size=16, verbose=0)
test_mse_score, test_mae_score = modle.evaluate(test_data, test_targets)

#층이 많으면 acc가 상승함.그러나 overfitting 조심
#노드가 많으면 overfitting이 빠르게 상승함.